/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or get player */
        post: operations["createPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player by ID */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player's game history */
        get: operations["getPlayerGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get leaderboard */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game by ID */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        CreatePlayerRequest: {
            username: string;
        };
        Player: {
            /** Format: uuid */
            id: string;
            username: string;
            wins: number;
            losses: number;
            draws: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LeaderboardEntry: {
            rank: number;
            username: string;
            wins: number;
            losses: number;
            draws: number;
            games: number;
        };
        GameRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            player1Id: string;
            /** Format: uuid */
            player2Id?: string | null;
            isBotGame: boolean;
            /** Format: uuid */
            winnerId?: string | null;
            /** @enum {string} */
            result?: "player1" | "player2" | "draw" | "forfeit";
            /** @description JSON-encoded moves */
            moves?: string;
            durationSeconds?: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
        };
        /** @enum {string} */
        WSMessageType: "join_queue" | "make_move" | "reconnect" | "leave_game" | "queue_joined" | "game_started" | "move_made" | "invalid_move" | "game_over" | "opponent_disconnected" | "opponent_reconnected" | "game_forfeited" | "error" | "game_state";
        WSMessage: {
            type: components["schemas"]["WSMessageType"];
            payload: Record<string, never>;
            /** Format: date-time */
            timestamp: string;
        };
        JoinQueuePayload: {
            username: string;
        };
        MakeMovePayload: {
            column: number;
        };
        ReconnectPayload: {
            gameId: string;
            username: string;
        };
        QueueJoinedPayload: {
            position: number;
        };
        GameStartedPayload: {
            gameId: string;
            opponent: string;
            yourTurn: boolean;
            /**
             * @description 1 = Red, 2 = Yellow
             * @enum {integer}
             */
            yourColor: 1 | 2;
        };
        /** @description 6 rows x 7 columns, 0=empty, 1=Player1, 2=Player2 */
        Board: number[][];
        MoveMadePayload: {
            column: number;
            row: number;
            /** @enum {integer} */
            player: 1 | 2;
            board: components["schemas"]["Board"];
        };
        InvalidMovePayload: {
            reason: string;
        };
        GameOverPayload: {
            /** @description username or 'draw' */
            winner: string;
            /** @enum {string} */
            result: "win" | "loss" | "draw" | "forfeit";
            finalBoard: components["schemas"]["Board"];
        };
        OpponentDisconnectedPayload: {
            /** @description seconds remaining for reconnect */
            timeout: number;
        };
        GameForfeitedPayload: {
            winner: string;
        };
        ErrorPayload: {
            message: string;
        };
        GameStatePayload: {
            gameId: string;
            board: components["schemas"]["Board"];
            /** @enum {integer} */
            currentTurn: 1 | 2;
            /** @enum {integer} */
            yourColor: 1 | 2;
            yourTurn: boolean;
            opponent: string;
        };
        GameState: {
            gameId: string;
            opponent: string;
            yourTurn: boolean;
            /** @enum {integer} */
            yourColor: 1 | 2;
            board: components["schemas"]["Board"];
        };
        GameOverState: {
            winner: string;
            /** @enum {string} */
            result: "win" | "loss" | "draw" | "forfeit";
            finalBoard?: components["schemas"]["Board"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    createPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlayerRequest"];
            };
        };
        responses: {
            /** @description Player created or retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlayerGames: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRecord"][];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top players */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRecord"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
